/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as HelpRouteImport } from './routes/help'
import { Route as TryRouteImport } from './routes/try'
import { Route as AuthenticatedAnalyzeRouteImport } from './routes/_authenticated/analyze'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated/billing'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedLabRouteImport } from './routes/_authenticated/lab'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedTeamRouteImport } from './routes/_authenticated/team'
import { Route as ApiRazorpayWebhookRouteImport } from './routes/api.razorpay-webhook'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as AuthenticatedAnalysesIndexRouteImport } from './routes/_authenticated/analyses.index'
import { Route as AuthenticatedAnalysesIdRouteImport } from './routes/_authenticated/analyses.$id'
import { Route as AuthenticatedDatasetsIndexRouteImport } from './routes/_authenticated/datasets.index'
import { Route as AuthenticatedDatasetsIdRouteImport } from './routes/_authenticated/datasets.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const TryRoute = TryRouteImport.update({
  id: '/try',
  path: '/try',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAnalyzeRoute = AuthenticatedAnalyzeRouteImport.update({
  id: '/analyze',
  path: '/analyze',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLabRoute = AuthenticatedLabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeamRoute = AuthenticatedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiRazorpayWebhookRoute = ApiRazorpayWebhookRouteImport.update({
  id: '/api/razorpay-webhook',
  path: '/api/razorpay-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAnalysesIndexRoute =
  AuthenticatedAnalysesIndexRouteImport.update({
    id: '/analyses/',
    path: '/analyses/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAnalysesIdRoute = AuthenticatedAnalysesIdRouteImport.update({
  id: '/analyses/$id',
  path: '/analyses/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDatasetsIndexRoute =
  AuthenticatedDatasetsIndexRouteImport.update({
    id: '/datasets/',
    path: '/datasets/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDatasetsIdRoute = AuthenticatedDatasetsIdRouteImport.update({
  id: '/datasets/$id',
  path: '/datasets/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/help': typeof HelpRoute
  '/try': typeof TryRoute
  '/analyze': typeof AuthenticatedAnalyzeRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/chat': typeof AuthenticatedChatRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/lab': typeof AuthenticatedLabRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/team': typeof AuthenticatedTeamRoute
  '/api/razorpay-webhook': typeof ApiRazorpayWebhookRoute
  '/invite/$token': typeof InviteTokenRoute
  '/analyses/$id': typeof AuthenticatedAnalysesIdRoute
  '/datasets/$id': typeof AuthenticatedDatasetsIdRoute
  '/analyses/': typeof AuthenticatedAnalysesIndexRoute
  '/datasets/': typeof AuthenticatedDatasetsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/help': typeof HelpRoute
  '/try': typeof TryRoute
  '/analyze': typeof AuthenticatedAnalyzeRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/chat': typeof AuthenticatedChatRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/lab': typeof AuthenticatedLabRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/team': typeof AuthenticatedTeamRoute
  '/api/razorpay-webhook': typeof ApiRazorpayWebhookRoute
  '/invite/$token': typeof InviteTokenRoute
  '/analyses/$id': typeof AuthenticatedAnalysesIdRoute
  '/datasets/$id': typeof AuthenticatedDatasetsIdRoute
  '/analyses': typeof AuthenticatedAnalysesIndexRoute
  '/datasets': typeof AuthenticatedDatasetsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/help': typeof HelpRoute
  '/try': typeof TryRoute
  '/_authenticated/analyze': typeof AuthenticatedAnalyzeRoute
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/chat': typeof AuthenticatedChatRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/lab': typeof AuthenticatedLabRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/team': typeof AuthenticatedTeamRoute
  '/api/razorpay-webhook': typeof ApiRazorpayWebhookRoute
  '/invite/$token': typeof InviteTokenRoute
  '/_authenticated/analyses/$id': typeof AuthenticatedAnalysesIdRoute
  '/_authenticated/datasets/$id': typeof AuthenticatedDatasetsIdRoute
  '/_authenticated/analyses/': typeof AuthenticatedAnalysesIndexRoute
  '/_authenticated/datasets/': typeof AuthenticatedDatasetsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/help'
    | '/try'
    | '/analyze'
    | '/billing'
    | '/chat'
    | '/dashboard'
    | '/lab'
    | '/settings'
    | '/team'
    | '/api/razorpay-webhook'
    | '/invite/$token'
    | '/analyses/$id'
    | '/datasets/$id'
    | '/analyses/'
    | '/datasets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/help'
    | '/try'
    | '/analyze'
    | '/billing'
    | '/chat'
    | '/dashboard'
    | '/lab'
    | '/settings'
    | '/team'
    | '/api/razorpay-webhook'
    | '/invite/$token'
    | '/analyses/$id'
    | '/datasets/$id'
    | '/analyses'
    | '/datasets'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/help'
    | '/try'
    | '/_authenticated/analyze'
    | '/_authenticated/billing'
    | '/_authenticated/chat'
    | '/_authenticated/dashboard'
    | '/_authenticated/lab'
    | '/_authenticated/settings'
    | '/_authenticated/team'
    | '/api/razorpay-webhook'
    | '/invite/$token'
    | '/_authenticated/analyses/$id'
    | '/_authenticated/datasets/$id'
    | '/_authenticated/analyses/'
    | '/_authenticated/datasets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  HelpRoute: typeof HelpRoute
  TryRoute: typeof TryRoute
  ApiRazorpayWebhookRoute: typeof ApiRazorpayWebhookRoute
  InviteTokenRoute: typeof InviteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/try': {
      id: '/try'
      path: '/try'
      fullPath: '/try'
      preLoaderRoute: typeof TryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/analyze': {
      id: '/_authenticated/analyze'
      path: '/analyze'
      fullPath: '/analyze'
      preLoaderRoute: typeof AuthenticatedAnalyzeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lab': {
      id: '/_authenticated/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof AuthenticatedLabRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/team': {
      id: '/_authenticated/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthenticatedTeamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/razorpay-webhook': {
      id: '/api/razorpay-webhook'
      path: '/api/razorpay-webhook'
      fullPath: '/api/razorpay-webhook'
      preLoaderRoute: typeof ApiRazorpayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/analyses/': {
      id: '/_authenticated/analyses/'
      path: '/analyses'
      fullPath: '/analyses/'
      preLoaderRoute: typeof AuthenticatedAnalysesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analyses/$id': {
      id: '/_authenticated/analyses/$id'
      path: '/analyses/$id'
      fullPath: '/analyses/$id'
      preLoaderRoute: typeof AuthenticatedAnalysesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/datasets/': {
      id: '/_authenticated/datasets/'
      path: '/datasets'
      fullPath: '/datasets/'
      preLoaderRoute: typeof AuthenticatedDatasetsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/datasets/$id': {
      id: '/_authenticated/datasets/$id'
      path: '/datasets/$id'
      fullPath: '/datasets/$id'
      preLoaderRoute: typeof AuthenticatedDatasetsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAnalyzeRoute: typeof AuthenticatedAnalyzeRoute
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedChatRoute: typeof AuthenticatedChatRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedLabRoute: typeof AuthenticatedLabRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTeamRoute: typeof AuthenticatedTeamRoute
  AuthenticatedAnalysesIdRoute: typeof AuthenticatedAnalysesIdRoute
  AuthenticatedDatasetsIdRoute: typeof AuthenticatedDatasetsIdRoute
  AuthenticatedAnalysesIndexRoute: typeof AuthenticatedAnalysesIndexRoute
  AuthenticatedDatasetsIndexRoute: typeof AuthenticatedDatasetsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAnalyzeRoute: AuthenticatedAnalyzeRoute,
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedChatRoute: AuthenticatedChatRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedLabRoute: AuthenticatedLabRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTeamRoute: AuthenticatedTeamRoute,
  AuthenticatedAnalysesIdRoute: AuthenticatedAnalysesIdRoute,
  AuthenticatedDatasetsIdRoute: AuthenticatedDatasetsIdRoute,
  AuthenticatedAnalysesIndexRoute: AuthenticatedAnalysesIndexRoute,
  AuthenticatedDatasetsIndexRoute: AuthenticatedDatasetsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  HelpRoute: HelpRoute,
  TryRoute: TryRoute,
  ApiRazorpayWebhookRoute: ApiRazorpayWebhookRoute,
  InviteTokenRoute: InviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
